spring.application.name=MakersHub
spring.datasource.url=jdbc:mysql://localhost:3306/makers_hub_db
spring.datasource.username=root
spring.datasource.password=mysql13
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


cloudinary.cloud-name=dt3qbekx0
cloudinary.api-key=856782166734916
cloudinary.api-secret=rERqBKTPF2KG8-hQ_gCWBtJHIMo

server.port=8080



# Enable logging of SQL queries
spring.jpa.show-sql=true

# Format SQL queries for readability
spring.jpa.properties.hibernate.format_sql=true

# Enable logging of JDBC statements
spring.datasource.hikari.connection-test-query=SELECT 1

# Log SQL query execution (including the bound parameters)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.com.example.MakersHub=DEBUG
logging.level.org.springframework=DEBUG

