//Authentication is a package for handling  sign in and login activites

package com.example.MakersHub.services.authentication;


import com.example.MakersHub.repository.UserRepository;
import com.example.MakersHub.dto.SignupRequestDTO;
import com.example.MakersHub.dto.UserDto;
import com.example.MakersHub.entity.User;
import com.example.MakersHub.enums.UserRole;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



@Service
public class AuthServiceImpl implements AuthService {
    private static final Logger logger = LoggerFactory.getLogger(AuthServiceImpl.class);

    @Autowired
    private UserRepository userRepository;

    public UserDto signUpClient(SignupRequestDTO signupRequestDTO) {

            logger.info("Received signup request from client: {}", signupRequestDTO);

        // Validate input
        if (signupRequestDTO == null) {
            throw new IllegalArgumentException("SignupRequestDTO cannot be null.");
        }
        if (signupRequestDTO.getEmail() == null || signupRequestDTO.getPassword() == null) {
            throw new IllegalArgumentException("Email and password are mandatory.");
        }

        // Check for existing email
        if (presentByEmail(signupRequestDTO.getEmail())) {
            throw new IllegalArgumentException("Email already exists.");
        }

         //Map DTO to entity
        User user = new User();
        user.setName(signupRequestDTO.getName());
        user.setLastname(signupRequestDTO.getLastname());
        user.setAddress(signupRequestDTO.getAddress());
        user.setEmail(signupRequestDTO.getEmail());
        user.setPhone(signupRequestDTO.getPhone());
        user.setPassword(new BCryptPasswordEncoder().encode(signupRequestDTO.getPassword()));
        user.setRole(UserRole.CLIENT);

        // Save and return DTO
        User savedUser = userRepository.save(user);
        return savedUser.getDto();


    }



    public UserDto signUpCrafter(SignupRequestDTO signupRequestDTO)
    {

       logger.info("Received signup request from crafter: {}", signupRequestDTO);
        // Validate input
        if (signupRequestDTO == null) {
            throw new IllegalArgumentException("SignupRequestDTO cannot be null.");
        }
        if (signupRequestDTO.getEmail() == null || signupRequestDTO.getPassword() == null) {
            throw new IllegalArgumentException("Email and password are mandatory.");
        }

        // Check for existing email
        if (presentByEmail(signupRequestDTO.getEmail())) {
            throw new IllegalArgumentException("Email already exists.");
        }

        User user = new User();
        user.setName(signupRequestDTO.getName());
        user.setLastname(signupRequestDTO.getLastname());
        user.setAddress(signupRequestDTO.getAddress());
        user.setEmail(signupRequestDTO.getEmail());
        user.setPhone(signupRequestDTO.getPhone());
        user.setPassword(new BCryptPasswordEncoder().encode(signupRequestDTO.getPassword()));

        user.setRole(UserRole.CRAFTER);

        return userRepository.save(user).getDto(); //getDo()->to convert user entity to userDto
   //After saving, it returns the saved object (the user in this case) with any field
        // that were any fields that were automatically updated,
        // like the id if it was generated by the database.

    }

    public Boolean presentByEmail(String email){
        return userRepository.findFirstByEmail(email)!=null;
    }

}
